### ISSUE TITLE
no such file to load -- action_controller/request (LoadError)

### ISSUE THREAD

**Issue by wakiki** [pelle/oauth#4]
I've upgraded to Rails 3 and one of my tests from your oauth_plugin controller isn't working. Doing a bit of digging around the problem appears to be in the oauth gem. I'm using the latest (0.4.3) oauth gem.

This line is in my spec file:

require 'oauth/client/action_controller_request'

Error:

/Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `require': no such file to load -- action_controller/request (LoadError)
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in`require'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:227:in `load_dependency'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in`require'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/oauth-0.4.3/lib/oauth/request_proxy/action_controller_request.rb:3
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `require'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in`require'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:227:in `load_dependency'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in`require'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/oauth-0.4.3/lib/oauth/client/action_controller_request.rb:2
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `require'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in`require'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:227:in `load_dependency'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in`require'
    from /Users/Steve/work/swom/spec/controllers/oauth_clients_controller_spec.rb:3
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:235:in `load'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:235:in`load'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:227:in `load_dependency'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:235:in`load'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/rspec-core-2.0.0.beta.20/lib/rspec/core/configuration.rb:302:in `load_spec_files'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/rspec-core-2.0.0.beta.20/lib/rspec/core/configuration.rb:302:in`map'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/rspec-core-2.0.0.beta.20/lib/rspec/core/configuration.rb:302:in `load_spec_files'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/rspec-core-2.0.0.beta.20/lib/rspec/core/command_line.rb:18:in`run'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/rspec-core-2.0.0.beta.20/lib/rspec/core/runner.rb:46:in `run_in_process'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/rspec-core-2.0.0.beta.20/lib/rspec/core/runner.rb:37:in`run'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/gems/rspec-core-2.0.0.beta.20/lib/rspec/core/runner.rb:10:in `autorun'
    from /Users/Steve/.rvm/gems/ree-1.8.7-2010.02@rails3/bin/rspec:19

Steve

**Comment by Bertg** [comment]
I have a similar issue...

**Comment by wakiki** [comment]
I believe I fixed this by updating to the latest version (I think the rails3 branch):
http://github.com/pelle/oauth-plugin/tree/rails3
